# Generated by Django 3.1.4 on 2020-12-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('Consultant', 'Consultant'), ('Sale', 'Sale'), ('Manager', 'Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='budget',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ielts',
            field=models.FloatField(null=True),
        ),
    ]
