# Generated by Django 3.1.4 on 2020-12-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201219_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='education',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Contact', 'Contact'), ('Pending', 'Pending'), ('Done', 'Done')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobavailable',
            name='education',
            field=models.IntegerField(null=True),
        ),
    ]
