# Generated by Django 3.1.4 on 2020-12-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobavailable',
            name='budget',
            field=models.BigIntegerField(null=True),
        ),
    ]
