# Generated by Django 3.1.4 on 2020-12-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201221_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
