# Generated by Django 3.1.4 on 2020-12-21 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
