# Generated by Django 3.1.4 on 2020-12-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201223_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
