# Generated by Django 3.1.4 on 2020-12-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201226_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'verbose_name': 'Theo dõi', 'verbose_name_plural': 'Theo dõi'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Thành viên', 'verbose_name_plural': 'Thành viên'},
        ),
        migrations.AlterField(
            model_name='level',
            name='ieltOverall',
            field=models.FloatField(choices=[('', 'IELTS Overall'), (4, '4.0'), (4.5, '4.5'), (5, '5.0'), (5.5, '5.5'), (6, '6.0'), (6.5, '6.5'), (7, '7.0')], null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='ieltsMin',
            field=models.FloatField(choices=[('', 'IELTS Minumum'), (4, '4.0'), (4.5, '4.5'), (5, '5.0'), (5.5, '5.5'), (6, '6.0'), (6.5, '6.5'), (7, '7.0')], null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='levelName',
            field=models.CharField(choices=[('Đại học', 'Đại học'), ('Sau đại học', 'Sau đại học'), ('Thạc sĩ', 'Thạc sĩ')], max_length=200, null=True),
        ),
    ]
