# Generated by Django 3.1.4 on 2020-12-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_guestcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcustomer',
            name='ielts_min',
            field=models.CharField(choices=[('', 'IELTS thấp nhất'), (4, '4.0'), (4.5, '4.5'), (5, '5.0'), (5.5, '5.5'), (6, '6.0'), (6.5, '6.5'), (7, '7.0')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guestcustomer',
            name='ielts_overall',
            field=models.CharField(choices=[('', 'IELTS trung bình'), (4, '4.0'), (4.5, '4.5'), (5, '5.0'), (5.5, '5.5'), (6, '6.0'), (6.5, '6.5'), (7, '7.0')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guestcustomer',
            name='level',
            field=models.CharField(choices=[('Đại học', 'Đại học'), ('Sau đại học', 'Sau đại học'), ('Thạc sĩ', 'Thạc sĩ')], max_length=50, null=True),
        ),
    ]
