# Generated by Django 3.1.4 on 2020-12-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201228_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestcustomer',
            options={'verbose_name': 'Khách vãng lai', 'verbose_name_plural': 'Khách vãng lai'},
        ),
        migrations.AlterField(
            model_name='guestcustomer',
            name='ielts_min',
            field=models.CharField(choices=[('', 'IELTS thấp nhất'), ('4', '4.0'), ('4.5', '4.5'), ('5', '5.0'), ('5.5', '5.5'), ('6', '6.0'), ('6.5', '6.5'), ('7', '7.0')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guestcustomer',
            name='ielts_overall',
            field=models.CharField(choices=[('', 'IELTS trung bình'), ('4', '4.0'), ('4.5', '4.5'), ('5', '5.0'), ('5.5', '5.5'), ('6', '6.0'), ('6.5', '6.5'), ('7', '7.0')], max_length=20, null=True),
        ),
    ]
