# Generated by Django 3.1.4 on 2020-12-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201231_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Thành phố',
                'verbose_name_plural': 'Thành phố',
            },
        ),
        migrations.RemoveField(
            model_name='guestcustomer',
            name='ielts_min',
        ),
        migrations.RemoveField(
            model_name='guestcustomer',
            name='ielts_overall',
        ),
        migrations.RemoveField(
            model_name='guestcustomer',
            name='level',
        ),
        migrations.AddField(
            model_name='guestcustomer',
            name='budget',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='guestcustomer',
            name='city_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='cities',
            field=models.ManyToManyField(related_name='uinversities', to='main.City'),
        ),
    ]
