# Generated by Django 3.1.4 on 2020-12-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201231_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='cities',
            field=models.ManyToManyField(to='main.City'),
        ),
    ]
