# Generated by Django 3.1.4 on 2020-12-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201231_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcustomer',
            name='level',
            field=models.CharField(choices=[('Đại học', 'Đại học'), ('Sau đại học', 'Sau đại học')], max_length=50, null=True),
        ),
    ]
