# Generated by Django 3.1.4 on 2021-01-02 09:27

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_guestcustomer_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('body', ckeditor.fields.RichTextField(null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Quản lý bài viết',
            },
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
