# Generated by Django 3.1.4 on 2021-01-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210102_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestcustomer',
            options={'verbose_name': 'Khách vãng lai', 'verbose_name_plural': 'Quản lý Khách vãng lai'},
        ),
        migrations.RenameField(
            model_name='level',
            old_name='ieltOverall',
            new_name='ielts_overall',
        ),
    ]
