# Generated by Django 3.1.4 on 2021-01-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_scholarship'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('facebook_url', models.CharField(max_length=200, null=True)),
                ('banner', models.ImageField(null=True, upload_to='')),
                ('banner_slogan_title_1', models.CharField(max_length=200, null=True)),
                ('banner_slogan_1', models.CharField(max_length=200, null=True)),
                ('banner_slogan_title_2', models.CharField(max_length=200, null=True)),
                ('banner_slogan_2', models.CharField(max_length=200, null=True)),
                ('banner_slogan_title_3', models.CharField(max_length=200, null=True)),
                ('banner_slogan_3', models.CharField(max_length=200, null=True)),
                ('feature_uni_baner', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'Trường', 'verbose_name_plural': 'Quản lý trường'},
        ),
    ]
