# Generated by Django 3.1.4 on 2021-01-03 05:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210103_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='team_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
