# Generated by Django 3.1.4 on 2021-01-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_pageinfo_team_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Quản lý khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Nhân viên', 'verbose_name_plural': 'Quản lý nhân viên'},
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='address_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='address_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pageinfo',
            name='page_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
