# Generated by Django 3.1.4 on 2021-01-03 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210103_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestcustomer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
