# Generated by Django 3.1.4 on 2021-01-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_guestcustomer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcustomer',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
