# Generated by Django 3.1.4 on 2021-01-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210104_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestcustomer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
