# Generated by Django 3.1.4 on 2021-01-04 15:00

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210104_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('pic', '370x240', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
