# Generated by Django 3.1.4 on 2021-01-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_university_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestcustomer',
            name='budget',
        ),
    ]
