# Generated by Django 3.1.4 on 2021-01-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_guestcustomer_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Nhóm ngành', 'verbose_name_plural': 'Quản lý nhóm ngành'},
        ),
        migrations.CreateModel(
            name='UniSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='uni_subjects',
            field=models.ManyToManyField(to='main.UniSubject'),
        ),
    ]
