# Generated by Django 3.1.4 on 2021-01-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210112_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['city_name'], 'verbose_name': 'Thành phố', 'verbose_name_plural': 'Thành phố'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subjectName'], 'verbose_name': 'Nhóm ngành', 'verbose_name_plural': 'Quản lý nhóm ngành'},
        ),
        migrations.AlterModelOptions(
            name='unisubject',
            options={'ordering': ['name'], 'verbose_name': 'Ngành nhỏ', 'verbose_name_plural': 'Quản lý ngành nhỏ'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['universityName'], 'verbose_name': 'Trường', 'verbose_name_plural': 'Quản lý trường'},
        ),
    ]
