# Generated by Django 3.1.4 on 2021-01-13 12:21

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20210113_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageinfo',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('banner', '420x1200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
