# Generated by Django 3.1.4 on 2021-01-15 14:04

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_pageinfo_cropping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unisubject',
            options={'ordering': ['name'], 'verbose_name': 'Khóa học', 'verbose_name_plural': 'Quản lý Khóa học'},
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('banner', '1200x420', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
