# Generated by Django 3.1.4 on 2021-01-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210115_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
