# Generated by Django 3.1.4 on 2021-02-12 12:11

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_subject_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='address_3',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='banner_slogan_1',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='banner_slogan_2',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='banner_slogan_3',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='banner_slogan_title_1',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='banner_slogan_title_2',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='banner_slogan_title_3',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pageinfo',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='article',
            name='img_description',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='university',
            name='show_on_homepage',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('banner', '1400x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.CreateModel(
            name='CustomerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=200, null=True)),
                ('school', models.CharField(max_length=200, null=True)),
                ('comment', models.CharField(max_length=200, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('body', models.CharField(max_length=200, null=True)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pageinfo')),
            ],
        ),
    ]
