# Generated by Django 3.1.4 on 2021-02-12 21:15

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20210212_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomment',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('img', '140x140', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('img', '1400x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
