# Generated by Django 3.1.4 on 2021-02-13 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20210213_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='name',
            new_name='levelName',
        ),
    ]
