# Generated by Django 3.1.4 on 2021-02-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20210213_0459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='levelName',
            new_name='name',
        ),
    ]
