# Generated by Django 3.1.4 on 2021-02-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_auto_20210214_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='youtube_url',
            field=models.URLField(null=True),
        ),
    ]
