# Generated by Django 3.1.4 on 2021-02-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_article_youtube_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='university',
            name='youtube_url',
            field=models.URLField(null=True),
        ),
    ]
