# Generated by Django 3.1.4 on 2021-02-14 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20210214_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='youtube_url',
        ),
    ]
